// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package manage_site_deduction

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	manageSiteDeductionFieldNames               []string
	manageSiteDeductionRows                     string
	manageSiteDeductionRowsExpectAutoFieldNames []string
	manageSiteDeductionRowsExpectAutoSet        string
)

const (
	Id              condition.Field = "id"
	Uuid            condition.Field = "uuid"
	CreateTime      condition.Field = "create_time"
	UpdateTime      condition.Field = "update_time"
	SiteUuid        condition.Field = "site_uuid"
	Score           condition.Field = "score"
	DeductionMethod condition.Field = "deduction_method"
	DeductionStatus condition.Field = "deduction_status"
	Remark          condition.Field = "remark"
	SiteName        condition.Field = "site_name"
	PriceCurrency   condition.Field = "price_currency"
	OperatorUuid    condition.Field = "operator_uuid"
)

func initManageSiteDeductionVars(flavor sqlbuilder.Flavor) {
	manageSiteDeductionFieldNames = condition.RawFieldNamesWithFlavor(flavor, &ManageSiteDeduction{})
	manageSiteDeductionRows = strings.Join(manageSiteDeductionFieldNames, ",")
	manageSiteDeductionRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, manageSiteDeductionFieldNames, "`id`", "`create_time`", "`update_time`")
	manageSiteDeductionRowsExpectAutoSet = strings.Join(manageSiteDeductionRowsExpectAutoFieldNames, ",")
}

type (
	manageSiteDeductionModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *ManageSiteDeduction) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *ManageSiteDeduction) error
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageSiteDeduction, error)
		FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageSiteDeduction, error)
		Update(ctx context.Context, session sqlx.Session, data *ManageSiteDeduction) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) manageSiteDeductionModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageSiteDeduction) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteDeduction, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ManageSiteDeduction, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ManageSiteDeduction, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ManageSiteDeduction, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ManageSiteDeduction, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteDeduction, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultManageSiteDeductionModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	ManageSiteDeduction struct {
		Id              int64     `db:"id"`
		Uuid            string    `db:"uuid"`
		CreateTime      time.Time `db:"create_time"`
		UpdateTime      time.Time `db:"update_time"`
		SiteUuid        string    `db:"site_uuid"`
		Score           float64   `db:"score"`
		DeductionMethod string    `db:"deduction_method"`
		DeductionStatus string    `db:"deduction_status"`
		Remark          string    `db:"remark"`
		SiteName        string    `db:"site_name"`
		PriceCurrency   string    `db:"price_currency"`
		OperatorUuid    string    `db:"operator_uuid"`
	}
)

func newManageSiteDeductionModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultManageSiteDeductionModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initManageSiteDeductionVars(o.Flavor)

	return &defaultManageSiteDeductionModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "manage_site_deduction"),
	}
}

// NewOriginalManageSiteDeductionModel returns a original model for the database table.
func NewOriginalManageSiteDeductionModel(conn sqlx.SqlConn) ManageSiteDeductionModel {
	return &customManageSiteDeductionModel{
		defaultManageSiteDeductionModel: newManageSiteDeductionModel(conn),
	}
}

func (m *defaultManageSiteDeductionModel) clone() *defaultManageSiteDeductionModel {
	return &defaultManageSiteDeductionModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultManageSiteDeductionModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageSiteDeductionModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageSiteDeduction, error) {
	sb := sqlbuilder.Select(manageSiteDeductionRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp ManageSiteDeduction
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageSiteDeductionModel) FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageSiteDeduction, error) {
	var resp ManageSiteDeduction
	var err error

	sb := sqlbuilder.Select(manageSiteDeductionRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "`uuid` = ?", uuid)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageSiteDeductionModel) Insert(ctx context.Context, session sqlx.Session, data *ManageSiteDeduction) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(manageSiteDeductionRowsExpectAutoSet).
		Values(data.Uuid, data.SiteUuid, data.Score, data.DeductionMethod, data.DeductionStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultManageSiteDeductionModel) InsertV2(ctx context.Context, session sqlx.Session, data *ManageSiteDeduction) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageSiteDeductionRowsExpectAutoSet).
			Values(data.Uuid, data.SiteUuid, data.Score, data.DeductionMethod, data.DeductionStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid).Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageSiteDeductionRowsExpectAutoSet).
			Values(data.Uuid, data.SiteUuid, data.Score, data.DeductionMethod, data.DeductionStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid).BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultManageSiteDeductionModel) Update(ctx context.Context, session sqlx.Session, data *ManageSiteDeduction) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "update_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "update_time"), data.UpdateTime))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "site_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "site_uuid"), data.SiteUuid))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "score")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "score"), data.Score))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "deduction_method")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "deduction_method"), data.DeductionMethod))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "deduction_status")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "deduction_status"), data.DeductionStatus))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "remark")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "remark"), data.Remark))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "site_name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "site_name"), data.SiteName))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "price_currency")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "price_currency"), data.PriceCurrency))
	}
	if slices.Contains(manageSiteDeductionRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "operator_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "operator_uuid"), data.OperatorUuid))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageSiteDeductionModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customManageSiteDeductionModel) WithTable(f func(table string) string) manageSiteDeductionModel {
	mc := &customManageSiteDeductionModel{
		defaultManageSiteDeductionModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customManageSiteDeductionModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageSiteDeduction) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(manageSiteDeductionRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Uuid, data.SiteUuid, data.Score, data.DeductionMethod, data.DeductionStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customManageSiteDeductionModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ManageSiteDeduction, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(manageSiteDeductionFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*ManageSiteDeduction
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customManageSiteDeductionModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ManageSiteDeduction, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customManageSiteDeductionModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteDeduction, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, manageSiteDeductionFieldNames, conditions...)
}

func (m *customManageSiteDeductionModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customManageSiteDeductionModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ManageSiteDeduction, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(manageSiteDeductionFieldNames), conditions...)
}

func (m *customManageSiteDeductionModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ManageSiteDeduction, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(manageSiteDeductionFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp ManageSiteDeduction
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customManageSiteDeductionModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteDeduction, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(manageSiteDeductionFieldNames...)...).From(m.table), conditions...)

	var resp []*ManageSiteDeduction
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customManageSiteDeductionModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customManageSiteDeductionModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
