CREATE TABLE `manage_site` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL UNIQUE,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `site_name` varchar(100) NOT NULL,
  `site_logo` varchar(500) NOT NULL,
  `price_currency` varchar(20) NOT NULL,
  `score_stat_type` varchar(20) NOT NULL,
  `status` varchar(1) NOT NULL,
  `remark` text NOT NULL,
  `db_host` varchar(255) NOT NULL,
  `db_username` varchar(100) NOT NULL,
  `db_password` varchar(255) NOT NULL,
  `db_port` bigint NOT NULL,
  `db_name` varchar(100) NOT NULL,
  `jwt_secret` varchar(255) NOT NULL,
  `admin_url` varchar(500) NOT NULL,
  `admin_username` varchar(50) NOT NULL,
  `contact_name` varchar(50) NOT NULL,
  `contact_phone` varchar(30) NOT NULL,
  `contact_email` varchar(100) NOT NULL,
  `remaining_score` decimal(20,2) NOT NULL DEFAULT 0,
  `total_topup` decimal(20,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
