// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package manage_site

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	manageSiteFieldNames               []string
	manageSiteRows                     string
	manageSiteRowsExpectAutoFieldNames []string
	manageSiteRowsExpectAutoSet        string
)

const (
	Id             condition.Field = "id"
	Uuid           condition.Field = "uuid"
	CreateTime     condition.Field = "create_time"
	UpdateTime     condition.Field = "update_time"
	SiteName       condition.Field = "site_name"
	SiteLogo       condition.Field = "site_logo"
	PriceCurrency  condition.Field = "price_currency"
	ScoreStatType  condition.Field = "score_stat_type"
	Status         condition.Field = "status"
	Remark         condition.Field = "remark"
	DbHost         condition.Field = "db_host"
	DbUsername     condition.Field = "db_username"
	DbPassword     condition.Field = "db_password"
	DbPort         condition.Field = "db_port"
	DbName         condition.Field = "db_name"
	JwtSecret      condition.Field = "jwt_secret"
	AdminUrl       condition.Field = "admin_url"
	AdminUsername  condition.Field = "admin_username"
	ContactName    condition.Field = "contact_name"
	ContactPhone   condition.Field = "contact_phone"
	ContactEmail   condition.Field = "contact_email"
	RemainingScore condition.Field = "remaining_score"
	TotalTopup     condition.Field = "total_topup"
)

func initManageSiteVars(flavor sqlbuilder.Flavor) {
	manageSiteFieldNames = condition.RawFieldNamesWithFlavor(flavor, &ManageSite{})
	manageSiteRows = strings.Join(manageSiteFieldNames, ",")
	manageSiteRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, manageSiteFieldNames, "`id`", "`create_time`", "`update_time`")
	manageSiteRowsExpectAutoSet = strings.Join(manageSiteRowsExpectAutoFieldNames, ",")
}

type (
	manageSiteModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *ManageSite) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *ManageSite) error
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageSite, error)
		FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageSite, error)
		Update(ctx context.Context, session sqlx.Session, data *ManageSite) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) manageSiteModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageSite) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSite, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ManageSite, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ManageSite, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ManageSite, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ManageSite, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSite, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultManageSiteModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	ManageSite struct {
		Id             int64     `db:"id"`
		Uuid           string    `db:"uuid"`
		CreateTime     time.Time `db:"create_time"`
		UpdateTime     time.Time `db:"update_time"`
		SiteName       string    `db:"site_name"`
		SiteLogo       string    `db:"site_logo"`
		PriceCurrency  string    `db:"price_currency"`
		ScoreStatType  string    `db:"score_stat_type"`
		Status         string    `db:"status"`
		Remark         string    `db:"remark"`
		DbHost         string    `db:"db_host"`
		DbUsername     string    `db:"db_username"`
		DbPassword     string    `db:"db_password"`
		DbPort         int64     `db:"db_port"`
		DbName         string    `db:"db_name"`
		JwtSecret      string    `db:"jwt_secret"`
		AdminUrl       string    `db:"admin_url"`
		AdminUsername  string    `db:"admin_username"`
		ContactName    string    `db:"contact_name"`
		ContactPhone   string    `db:"contact_phone"`
		ContactEmail   string    `db:"contact_email"`
		RemainingScore float64   `db:"remaining_score"`
		TotalTopup     float64   `db:"total_topup"`
	}
)

func newManageSiteModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultManageSiteModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initManageSiteVars(o.Flavor)

	return &defaultManageSiteModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "manage_site"),
	}
}

// NewOriginalManageSiteModel returns a original model for the database table.
func NewOriginalManageSiteModel(conn sqlx.SqlConn) ManageSiteModel {
	return &customManageSiteModel{
		defaultManageSiteModel: newManageSiteModel(conn),
	}
}

func (m *defaultManageSiteModel) clone() *defaultManageSiteModel {
	return &defaultManageSiteModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultManageSiteModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageSiteModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageSite, error) {
	sb := sqlbuilder.Select(manageSiteRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp ManageSite
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageSiteModel) FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageSite, error) {
	var resp ManageSite
	var err error

	sb := sqlbuilder.Select(manageSiteRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "`uuid` = ?", uuid)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageSiteModel) Insert(ctx context.Context, session sqlx.Session, data *ManageSite) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(manageSiteRowsExpectAutoSet).
		Values(data.Uuid, data.SiteName, data.SiteLogo, data.PriceCurrency, data.ScoreStatType, data.Status, data.Remark, data.DbHost, data.DbUsername, data.DbPassword, data.DbPort, data.DbName, data.JwtSecret, data.AdminUrl, data.AdminUsername, data.ContactName, data.ContactPhone, data.ContactEmail, data.RemainingScore, data.TotalTopup).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultManageSiteModel) InsertV2(ctx context.Context, session sqlx.Session, data *ManageSite) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageSiteRowsExpectAutoSet).
			Values(data.Uuid, data.SiteName, data.SiteLogo, data.PriceCurrency, data.ScoreStatType, data.Status, data.Remark, data.DbHost, data.DbUsername, data.DbPassword, data.DbPort, data.DbName, data.JwtSecret, data.AdminUrl, data.AdminUsername, data.ContactName, data.ContactPhone, data.ContactEmail, data.RemainingScore, data.TotalTopup).Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageSiteRowsExpectAutoSet).
			Values(data.Uuid, data.SiteName, data.SiteLogo, data.PriceCurrency, data.ScoreStatType, data.Status, data.Remark, data.DbHost, data.DbUsername, data.DbPassword, data.DbPort, data.DbName, data.JwtSecret, data.AdminUrl, data.AdminUsername, data.ContactName, data.ContactPhone, data.ContactEmail, data.RemainingScore, data.TotalTopup).BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultManageSiteModel) Update(ctx context.Context, session sqlx.Session, data *ManageSite) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "update_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "update_time"), data.UpdateTime))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "site_name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "site_name"), data.SiteName))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "site_logo")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "site_logo"), data.SiteLogo))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "price_currency")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "price_currency"), data.PriceCurrency))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "score_stat_type")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "score_stat_type"), data.ScoreStatType))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "status")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "status"), data.Status))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "remark")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "remark"), data.Remark))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "db_host")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "db_host"), data.DbHost))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "db_username")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "db_username"), data.DbUsername))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "db_password")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "db_password"), data.DbPassword))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "db_port")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "db_port"), data.DbPort))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "db_name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "db_name"), data.DbName))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "jwt_secret")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "jwt_secret"), data.JwtSecret))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "admin_url")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "admin_url"), data.AdminUrl))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "admin_username")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "admin_username"), data.AdminUsername))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "contact_name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "contact_name"), data.ContactName))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "contact_phone")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "contact_phone"), data.ContactPhone))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "contact_email")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "contact_email"), data.ContactEmail))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "remaining_score")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "remaining_score"), data.RemainingScore))
	}
	if slices.Contains(manageSiteRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "total_topup")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "total_topup"), data.TotalTopup))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageSiteModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customManageSiteModel) WithTable(f func(table string) string) manageSiteModel {
	mc := &customManageSiteModel{
		defaultManageSiteModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customManageSiteModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageSite) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(manageSiteRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Uuid, data.SiteName, data.SiteLogo, data.PriceCurrency, data.ScoreStatType, data.Status, data.Remark, data.DbHost, data.DbUsername, data.DbPassword, data.DbPort, data.DbName, data.JwtSecret, data.AdminUrl, data.AdminUsername, data.ContactName, data.ContactPhone, data.ContactEmail, data.RemainingScore, data.TotalTopup)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customManageSiteModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ManageSite, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(manageSiteFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*ManageSite
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customManageSiteModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ManageSite, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customManageSiteModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSite, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, manageSiteFieldNames, conditions...)
}

func (m *customManageSiteModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customManageSiteModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ManageSite, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(manageSiteFieldNames), conditions...)
}

func (m *customManageSiteModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ManageSite, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(manageSiteFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp ManageSite
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customManageSiteModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSite, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(manageSiteFieldNames...)...).From(m.table), conditions...)

	var resp []*ManageSite
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customManageSiteModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customManageSiteModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
