// Code generated by jzero. DO NOT EDIT.
package v1managesite_topup

import (
	"time"
)

var (
	_ = time.Now()
)

type AddRequest struct {
	SiteUuid    string `json:"siteUuid"`
	Score       string `json:"score"`
	TopupMethod string `json:"topupMethod"`
	TopupStatus string `json:"topupStatus,optional"`
	Remark      string `json:"remark,optional"`
}

type AddResponse struct {
}

type ListRequest struct {
	PageRequest
	SiteUuid    string `form:"siteUuid,optional"`
	TopupStatus string `form:"topupStatus,optional"`
	SiteName    string `form:"siteName,optional"`
}

type ListResponse struct {
	PageResponse
	Records []ManageSiteTopup `json:"records"`
}

type ManageSiteTopup struct {
	Uuid          string `json:"uuid"`
	SiteUuid      string `json:"siteUuid"`
	Score         string `json:"score"`
	TopupMethod   string `json:"topupMethod"`
	TopupStatus   string `json:"topupStatus"`
	Remark        string `json:"remark"`
	SiteName      string `json:"siteName"`
	PriceCurrency string `json:"priceCurrency"`
	OperatorUuid  string `json:"operatorUuid"`
	CreateTime    string `json:"createTime"`
	UpdateTime    string `json:"updateTime"`
}

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}
