// Code generated by jzero. DO NOT EDIT.
package v1managesite

import (
	"time"
)

var (
	_ = time.Now()
)

type AddRequest struct {
	SiteName      string `json:"siteName"`
	SiteLogo      string `json:"siteLogo,optional"`
	PriceCurrency string `json:"priceCurrency"`
	ScoreStatType string `json:"scoreStatType,optional"`
	Status        string `json:"status,default=1"`
	Remark        string `json:"remark,optional"`
	DbHost        string `json:"dbHost"`
	DbUsername    string `json:"dbUsername"`
	DbPassword    string `json:"dbPassword"`
	DbPort        int64  `json:"dbPort"`
	DbName        string `json:"dbName"`
	JwtSecret     string `json:"jwtSecret"`
	AdminUrl      string `json:"adminUrl"`
	AdminUsername string `json:"adminUsername"`
	ContactName   string `json:"contactName,optional"`
	ContactPhone  string `json:"contactPhone,optional"`
	ContactEmail  string `json:"contactEmail,optional"`
}

type AddResponse struct {
}

type DeleteRequest struct {
	Uuids []string `json:"uuids"`
}

type DeleteResponse struct {
}

type EditRequest struct {
	Uuid          string `json:"uuid"`
	SiteName      string `json:"siteName"`
	SiteLogo      string `json:"siteLogo,optional"`
	PriceCurrency string `json:"priceCurrency"`
	ScoreStatType string `json:"scoreStatType,optional"`
	Status        string `json:"status"`
	Remark        string `json:"remark,optional"`
	DbHost        string `json:"dbHost"`
	DbUsername    string `json:"dbUsername"`
	DbPassword    string `json:"dbPassword"`
	DbPort        int64  `json:"dbPort"`
	DbName        string `json:"dbName"`
	JwtSecret     string `json:"jwtSecret"`
	AdminUrl      string `json:"adminUrl"`
	AdminUsername string `json:"adminUsername"`
	ContactName   string `json:"contactName,optional"`
	ContactPhone  string `json:"contactPhone,optional"`
	ContactEmail  string `json:"contactEmail,optional"`
}

type EditResponse struct {
}

type GetAllRequest struct {
}

type GetAllResponse struct {
	Uuid          string `json:"uuid"`
	SiteName      string `json:"siteName"`
	PriceCurrency string `json:"priceCurrency"`
}

type ListRequest struct {
	PageRequest
	SiteName      string `form:"siteName,optional"`
	PriceCurrency string `form:"priceCurrency,optional"`
	Status        string `form:"status,optional"`
}

type ListResponse struct {
	PageResponse
	Records []ManageSite `json:"records"`
}

type ManageSite struct {
	Uuid           string `json:"uuid"`
	SiteName       string `json:"siteName"`
	SiteLogo       string `json:"siteLogo"`
	PriceCurrency  string `json:"priceCurrency"`
	ScoreStatType  string `json:"scoreStatType"`
	Status         string `json:"status"`
	Remark         string `json:"remark"`
	DbHost         string `json:"dbHost"`
	DbUsername     string `json:"dbUsername"`
	DbPassword     string `json:"dbPassword"`
	DbPort         int64  `json:"dbPort"`
	DbName         string `json:"dbName"`
	JwtSecret      string `json:"jwtSecret"`
	AdminUrl       string `json:"adminUrl"`
	AdminUsername  string `json:"adminUsername"`
	ContactName    string `json:"contactName"`
	ContactPhone   string `json:"contactPhone"`
	ContactEmail   string `json:"contactEmail"`
	RemainingScore string `json:"remainingScore"`
	TotalTopup     string `json:"totalTopup"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type PageRequest struct {
	Current int `form:"current,default=1,optional"`
	Size    int `form:"size,default=10,optional"`
}

type PageResponse struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}
