// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package manage_site_topup

import (
	"context"
	"database/sql"
	"slices"
	"strings"
	"time"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	manageSiteTopupFieldNames               []string
	manageSiteTopupRows                     string
	manageSiteTopupRowsExpectAutoFieldNames []string
	manageSiteTopupRowsExpectAutoSet        string
)

const (
	Id            condition.Field = "id"
	Uuid          condition.Field = "uuid"
	CreateTime    condition.Field = "create_time"
	UpdateTime    condition.Field = "update_time"
	SiteUuid      condition.Field = "site_uuid"
	Score         condition.Field = "score"
	TopupMethod   condition.Field = "topup_method"
	TopupStatus   condition.Field = "topup_status"
	Remark        condition.Field = "remark"
	SiteName      condition.Field = "site_name"
	PriceCurrency condition.Field = "price_currency"
	OperatorUuid  condition.Field = "operator_uuid"
)

func initManageSiteTopupVars(flavor sqlbuilder.Flavor) {
	manageSiteTopupFieldNames = condition.RawFieldNamesWithFlavor(flavor, &ManageSiteTopup{})
	manageSiteTopupRows = strings.Join(manageSiteTopupFieldNames, ",")
	manageSiteTopupRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, manageSiteTopupFieldNames, "`id`", "`create_time`", "`update_time`")
	manageSiteTopupRowsExpectAutoSet = strings.Join(manageSiteTopupRowsExpectAutoFieldNames, ",")
}

type (
	manageSiteTopupModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *ManageSiteTopup) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *ManageSiteTopup) error
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageSiteTopup, error)
		FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageSiteTopup, error)
		Update(ctx context.Context, session sqlx.Session, data *ManageSiteTopup) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) manageSiteTopupModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageSiteTopup) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteTopup, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ManageSiteTopup, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ManageSiteTopup, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ManageSiteTopup, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ManageSiteTopup, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteTopup, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultManageSiteTopupModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	ManageSiteTopup struct {
		Id            int64     `db:"id"`
		Uuid          string    `db:"uuid"`
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
		SiteUuid      string    `db:"site_uuid"`
		Score         float64   `db:"score"`
		TopupMethod   string    `db:"topup_method"`
		TopupStatus   string    `db:"topup_status"`
		Remark        string    `db:"remark"`
		SiteName      string    `db:"site_name"`
		PriceCurrency string    `db:"price_currency"`
		OperatorUuid  string    `db:"operator_uuid"`
	}
)

func newManageSiteTopupModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultManageSiteTopupModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initManageSiteTopupVars(o.Flavor)

	return &defaultManageSiteTopupModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "manage_site_topup"),
	}
}

// NewOriginalManageSiteTopupModel returns a original model for the database table.
func NewOriginalManageSiteTopupModel(conn sqlx.SqlConn) ManageSiteTopupModel {
	return &customManageSiteTopupModel{
		defaultManageSiteTopupModel: newManageSiteTopupModel(conn),
	}
}

func (m *defaultManageSiteTopupModel) clone() *defaultManageSiteTopupModel {
	return &defaultManageSiteTopupModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultManageSiteTopupModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageSiteTopupModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*ManageSiteTopup, error) {
	sb := sqlbuilder.Select(manageSiteTopupRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp ManageSiteTopup
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageSiteTopupModel) FindOneByUuid(ctx context.Context, session sqlx.Session, uuid string) (*ManageSiteTopup, error) {
	var resp ManageSiteTopup
	var err error

	sb := sqlbuilder.Select(manageSiteTopupRows).From(m.table)
	condition.SelectByWhereRawSql(sb, "`uuid` = ?", uuid)
	sb.Limit(1)

	sql, args := sb.BuildWithFlavor(m.flavor)

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManageSiteTopupModel) Insert(ctx context.Context, session sqlx.Session, data *ManageSiteTopup) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(manageSiteTopupRowsExpectAutoSet).
		Values(data.Uuid, data.SiteUuid, data.Score, data.TopupMethod, data.TopupStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid).BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultManageSiteTopupModel) InsertV2(ctx context.Context, session sqlx.Session, data *ManageSiteTopup) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageSiteTopupRowsExpectAutoSet).
			Values(data.Uuid, data.SiteUuid, data.Score, data.TopupMethod, data.TopupStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid).Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(manageSiteTopupRowsExpectAutoSet).
			Values(data.Uuid, data.SiteUuid, data.Score, data.TopupMethod, data.TopupStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid).BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultManageSiteTopupModel) Update(ctx context.Context, session sqlx.Session, data *ManageSiteTopup) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "uuid"), data.Uuid))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "create_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "create_time"), data.CreateTime))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "update_time")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "update_time"), data.UpdateTime))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "site_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "site_uuid"), data.SiteUuid))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "score")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "score"), data.Score))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "topup_method")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "topup_method"), data.TopupMethod))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "topup_status")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "topup_status"), data.TopupStatus))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "remark")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "remark"), data.Remark))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "site_name")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "site_name"), data.SiteName))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "price_currency")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "price_currency"), data.PriceCurrency))
	}
	if slices.Contains(manageSiteTopupRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "operator_uuid")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "operator_uuid"), data.OperatorUuid))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultManageSiteTopupModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customManageSiteTopupModel) WithTable(f func(table string) string) manageSiteTopupModel {
	mc := &customManageSiteTopupModel{
		defaultManageSiteTopupModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customManageSiteTopupModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*ManageSiteTopup) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(manageSiteTopupRowsExpectAutoSet)

	for _, data := range datas {
		sb.Values(data.Uuid, data.SiteUuid, data.Score, data.TopupMethod, data.TopupStatus, data.Remark, data.SiteName, data.PriceCurrency, data.OperatorUuid)
	}

	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customManageSiteTopupModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*ManageSiteTopup, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(manageSiteTopupFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*ManageSiteTopup
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customManageSiteTopupModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*ManageSiteTopup, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customManageSiteTopupModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteTopup, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, manageSiteTopupFieldNames, conditions...)
}

func (m *customManageSiteTopupModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customManageSiteTopupModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*ManageSiteTopup, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(manageSiteTopupFieldNames), conditions...)
}

func (m *customManageSiteTopupModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*ManageSiteTopup, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(manageSiteTopupFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp ManageSiteTopup
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customManageSiteTopupModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*ManageSiteTopup, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(manageSiteTopupFieldNames...)...).From(m.table), conditions...)

	var resp []*ManageSiteTopup
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customManageSiteTopupModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customManageSiteTopupModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
